//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BoostTestUi.rc
//
#define ID_ITERATIONS_PANE              1
#define ID_TOTAL_PANE                   2
#define ID_RUN_PANE                     3
#define ID_FAILED_PANE                  4
#define IDD_ABOUTBOX                    100
#define IDD_BOOSTHELP                   101
#define IDD_CATCHHELP                   102
#define IDD_CATCH2HELP                  103
#define IDD_GOOGLEHELP                  104
#define IDD_NUNITHELP                   105
#define IDD_SELECT_DEVENV               106
#define IDR_MAINFRAME                   128
#define IDR_APPNAME                     129
#define IDR_UNIT_TEST_GUI_HPP           200
#define IDR_CATCH_GUI_HPP               201
#define IDR_CATCH2_GUI_HPP              202
#define IDR_GTEST_GUI_H                 203
#define IDR_BOOSTTESTSAMPLE_RTF         204
#define IDR_CATCHTESTSAMPLE_RTF         205
#define IDR_CATCH2TESTSAMPLE_RTF        206
#define IDR_GOOGLETESTSAMPLE_RTF        207
#define IDR_NUNITSAMPLE_RTF             208
#define IDI_EMPTY                       209
#define IDI_RUN                         210
#define IDI_TICK                        211
#define IDI_CROSS                       212
#define IDR_LOGLEVEL_MENU               213
#define IDR_TREE_CONTEXTMENU            214
#define IDD_AUTORUN                     215
#define IDI_TICKG                       216
#define IDD_CATEGORIES                  217
#define IDD_OPTIONS                     218
#define IDD_ARGUMENTS                   219
#define IDD_FIND                        220
#define IDI_WARN                        221
#define IDD_SELECT_DEBUG                222
#define IDC_TREEVIEW                    1000
#define IDC_PROGRESSBAR                 1001
#define IDC_LOGVIEW                     1002
#define IDC_BOOST_URL                   1003
#define IDC_COUNT                       1004
#define IDC_COUNT_SPIN                  1005
#define IDC_CONTINUE                    1007
#define IDC_UNLIMITED                   1008
#define IDC_RANDOMIZE                   1009
#define IDC_DATE                        1010
#define IDC_VERSION                     1011
#define IDC_DESCRIPTION                 1012
#define IDC_SAMPLE                      1013
#define IDC_SEEALSO                     1014
#define IDC_URL                         1015
#define IDC_INCLUDE_LIST                1019
#define IDC_EXCLUDE_LIST                1020
#define IDC_ALL                         1021
#define IDC_NONE                        1022
#define IDC_INCLUDE                     1023
#define IDC_EXCLUDE                     1024
#define IDC_INCLUDE_LABEL               1025
#define IDC_EXCLUDE_LABEL               1026
#define IDC_INVISIBLE                   1027
#define IDC_ARGUMENTS                   1028
#define IDC_TEXT                        1028
#define IDC_PREVIOUS                    1029
#define IDC_NEXT                        1030
#define IDC_DEVENV_LIST                 1031
#define IDC_AUTO                        1032
#define IDC_TYPE                        1033
#define IDC_LIST                        1034
#define IDC_TREE                        1035
#define IDC_EDIT1                       1036
#define IDC_DELAY                       1036
#define IDC_SPIN                        1037
#define ID_TEST_ABORT                   32775
#define ID_LOG_SELECTALL                32776
#define ID_LOG_CLEARSELECTION           32777
#define ID_LOG_COPY                     32778
#define ID_LOG_CLEARDISPLAY             32779
#define ID_LOG_CLEAR                    32780
#define ID_TEST_RANDOMIZE               32781
#define ID_TEST_DEBUGGER                32782
#define ID_TEST_WAITFORDEBUGGER         32783
#define ID_LOG_AUTO_CLEAR               32784
#define ID_LOG_AUTOCLEARLOG             32785
#define ID_FILE_AUTO_RUN                32786
#define ID_FILE_CREATE_BOOST_HPP        32787
#define ID_FILE_CREATE_CATCH_HPP        32788
#define ID_FILE_CREATE_CATCH2_HPP       32789
#define ID_FILE_CREATE_GOOGLE_HPP       32790
#define ID_LOGLEVEL                     32791
#define ID_TREE_RUN                     32792
#define ID_TREE_RUN_CHECKED             32793
#define ID_TREE_RUN_ALL                 32794
#define ID_TREE_CHECK                   32795
#define ID_TREE_CHECK_ALL               32796
#define ID_TREE_UNCHECK_ALL             32797
#define ID_TREE_CHECK_FAILED            32798
#define ID_TREE_COPY_NAME               32799
#define ID_TREE_COPY_COMMAND            32800
#define IDR_LIST_CONTEXTMENU            32801
#define IDR_SAMPLE_CONTEXTMENU          32802
#define ID_SAMPLE_COPY                  32803
#define ID_TREE_WAITFORDEBUGGER         32804
#define ID_TEST_REPEAT                  32805
#define ID_HELP_BOOST                   32806
#define ID_HELP_CATCH                   32807
#define ID_HELP_CATCH2                  32808
#define ID_HELP_GOOGLE                  32809
#define ID_HELP_NUNIT                   32810
#define ID_LOG_TIME                     32811
#define ID_LOG_SHOWCLOCKTIME            32812
#define ID_RESET_SELECTION              32813
#define ID_TEST_CATEGORIES              32814
#define ID_TEST_OPTIONS                 32815
#define ID_TEST_COMMANDLINEARGS         32816
#define ID_TEST_RUNNERARGS              32817
#define ID_LOG_FIND                     32818
#define ID_PROGRESS                     32819

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        223
#define _APS_NEXT_COMMAND_VALUE         32820
#define _APS_NEXT_CONTROL_VALUE         1038
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
